In [4]:
import pandas as pd

In [5]:
player_df_final = pd.read_csv('player_data_final.csv')
player_df_final.head()

,ID,points,player,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER
0,1,1893.0,player1,1251.8,97.8,63.0,33.9,0.569,17.2,11.5,26.1,4.7,23.3,7.8,10.90000
1,2,1386.0,player2,1282.5,110.5,58.0,32.5,0.511,24.8,9.7,26.9,6.1,0.9,10.7,27.30000
2,3,1405.0,player3,1252.3,105.8,55.0,36.3,0.605,25.7,13.9,28.1,4.5,4.9,1.8,16.59464
3,4,1282.0,player4,1235.9,100.7,54.0,37.6,0.636,29.5,11.0,22.3,4.8,4.6,5.6,22.35000
4,5,1721.0,player5,1254.0,105.7,59.0,30.5,0.589,22.8,9.9,24.6,1.2,8.4,12.1,28.38000

In [6]:
ts_df = player_df_final.iloc[26: , :]
ts_df

,ID,points,player,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER
26,31,2049.0,tune_squad1,1434.0,110.0,64.000000,38.800000,0.619,31.5,14.9,35.5,8.3,17.6,12.8,28.440000
27,32,1795.0,tune_squad2,1481.8,112.1,62.000000,35.400000,0.608,31.9,14.5,32.0,6.5,22.5,12.9,23.340000
28,33,1805.0,tune_squad3,1509.9,108.6,64.000000,35.400000,0.622,27.9,13.9,36.0,5.9,27.7,12.2,22.410000
29,34,1743.0,tune_squad4,1422.4,112.9,64.000000,36.300000,0.619,30.9,15.6,34.5,5.9,18.9,14.8,29.850844
30,35,1963.0,tune_squad5,1539.1,117.4,59.529412,35.157143,0.633,32.3,16.2,34.0,5.9,19.8,13.1,27.160000
31,36,2062.0,tune_squad6,1505.7,111.5,59.529412,37.000000,0.620,29.8,15.6,36.2,4.9,23.9,14.7,27.860000
32,37,1845.0,tune_squad7,1435.7,113.1,69.000000,36.900000,0.634,33.2,14.0,36.5,4.1,21.5,16.4,34.260000
33,38,1778.0,tune_squad8,1526.4,109.3,66.000000,34.900000,0.612,30.6,15.9,35.9,5.5,18.8,13.7,28.650000
34,39,1901.0,tune_squad9,1444.1,109.7,67.000000,36.500000,0.609,27.2,14.8,35.5,5.0,21.8,8.9,20.120000
35,42,1631.0,tune_squad12,1465.7,110.1,66.000000,37.500000,0.613,28.4,14.4,35.7,6.5,20.7,14.0,28.400000
36,43,1828.0,tune_squad13,1507.2,112.7,64.000000,36.500000,0.618,31.3,14.0,34.9,5.9,21.3,14.5,29.092625
37,44,1821.0,tune_squad14,1443.7,118.8,66.000000,36.600000,0.609,27.3,13.5,35.8,7.0,23.8,11.5,22.960000
38,45,1740.0,tune_squad15,1443.9,114.1,68.000000,37.100000,0.611,26.6,15.2,29.3,8.3,17.7,11.1,21.220000
39,46,1993.0,tune_squad16,1459.0,112.5,59.529412,36.900000,0.627,30.4,15.0,33.7,6.3,19.3,14.1,28.760000

In [8]:
ts_name_df = pd.read_csv('tune_squad.csv', sep='\t')
ts_name_df

    ID              player
0   31           Sylvester
1   32  Marvin the Martian
2   33         Road Runner
3   34     Foghorn Leghorn
4   35          Bugs Bunny
5   36          Elmer Fudd
6   37          Lola Bunny
7   38           Porky Pig
8   39     Tasmanian Devil
9   40        Yosemite Sam
10  41            Gossamer
11  42              Granny
12  43      Wile E. Coyote
13  44              Tweety
14  45            Penelope
15  46          Daffy Duck

In [9]:
ts_df = pd.merge(ts_df, ts_name_df, on='ID', how='left', suffixes=('_type', '_name'))
ts_df.head()

,ID,points,player_type,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER,player_name
0,31,2049.0,tune_squad1,1434.0,110.0,64.000000,38.800000,0.619,31.5,14.9,35.5,8.3,17.6,12.8,28.440000,Sylvester
1,32,1795.0,tune_squad2,1481.8,112.1,62.000000,35.400000,0.608,31.9,14.5,32.0,6.5,22.5,12.9,23.340000,Marvin the Martian
2,33,1805.0,tune_squad3,1509.9,108.6,64.000000,35.400000,0.622,27.9,13.9,36.0,5.9,27.7,12.2,22.410000,Road Runner
3,34,1743.0,tune_squad4,1422.4,112.9,64.000000,36.300000,0.619,30.9,15.6,34.5,5.9,18.9,14.8,29.850844,Foghorn Leghorn
4,35,1963.0,tune_squad5,1539.1,117.4,59.529412,35.157143,0.633,32.3,16.2,34.0,5.9,19.8,13.1,27.160000,Bugs Bunny

In [16]:
ts_df.insert(1, 'player_name', ts_df.pop('player_name'))
ts_df.drop('player_type', axis=1, inplace=True)
ts_df

,ID,player_name,points,possessions,team_pace,GP,MPG,TS%,AST,TO,USG,ORR,DRR,REBR,PER
0,31,Sylvester,2049.0,1434.0,110.0,64.000000,38.800000,0.619,31.5,14.9,35.5,8.3,17.6,12.8,28.440000
1,32,Marvin the Martian,1795.0,1481.8,112.1,62.000000,35.400000,0.608,31.9,14.5,32.0,6.5,22.5,12.9,23.340000
2,33,Road Runner,1805.0,1509.9,108.6,64.000000,35.400000,0.622,27.9,13.9,36.0,5.9,27.7,12.2,22.410000
3,34,Foghorn Leghorn,1743.0,1422.4,112.9,64.000000,36.300000,0.619,30.9,15.6,34.5,5.9,18.9,14.8,29.850844
4,35,Bugs Bunny,1963.0,1539.1,117.4,59.529412,35.157143,0.633,32.3,16.2,34.0,5.9,19.8,13.1,27.160000
5,36,Elmer Fudd,2062.0,1505.7,111.5,59.529412,37.000000,0.620,29.8,15.6,36.2,4.9,23.9,14.7,27.860000
6,37,Lola Bunny,1845.0,1435.7,113.1,69.000000,36.900000,0.634,33.2,14.0,36.5,4.1,21.5,16.4,34.260000
7,38,Porky Pig,1778.0,1526.4,109.3,66.000000,34.900000,0.612,30.6,15.9,35.9,5.5,18.8,13.7,28.650000
8,39,Tasmanian Devil,1901.0,1444.1,109.7,67.000000,36.500000,0.609,27.2,14.8,35.5,5.0,21.8,8.9,20.120000
9,42,Granny,1631.0,1465.7,110.1,66.000000,37.500000,0.613,28.4,14.4,35.7,6.5,20.7,14.0,28.400000
10,43,Wile E. Coyote,1828.0,1507.2,112.7,64.000000,36.500000,0.618,31.3,14.0,34.9,5.9,21.3,14.5,29.092625
11,44,Tweety,1821.0,1443.7,118.8,66.000000,36.600000,0.609,27.3,13.5,35.8,7.0,23.8,11.5,22.960000
12,45,Penelope,1740.0,1443.9,114.1,68.000000,37.100000,0.611,26.6,15.2,29.3,8.3,17.7,11.1,21.220000
13,46,Daffy Duck,1993.0,1459.0,112.5,59.529412,36.900000,0.627,30.4,15.0,33.7,6.3,19.3,14.1,28.760000

In [28]:
game_stat_cols = list(ts_df.iloc[:, 7:-1])
stdevs_s = ts_df[game_stat_cols].std()
stdevs_s

TS%     0.008574
AST     2.113601
TO      0.817293
USG     1.963583
ORR     1.176510
DRR     2.778617
REBR    1.870608
dtype: float64

In [29]:
from sklearn.linear_model import LinearRegression
from numpy.random import randn

X = player_df_final.iloc[:, 7:-1].to_numpy()
y = player_df_final.iloc[:, -1]

In [31]:
lin_reg = LinearRegression()
lin_reg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
print('Iteration # \thigh PER \tlow PER')

for i in range(10):
    game_df = pd.DataFrame(columns=game_stat_cols, index=list(ts_df['player_name']))

    for stat in game_stat_cols:
        game_df[stat] = list(ts_df[stat] + randn(len(ts_df)) * stdevs_s[stat])

    game_df['PER'] = lin_reg.predict(game_df)
    print('Iteration {}'.format(i+1) + ' \t' + game_df['PER'].idxmax() + ' \t' + game_df['PER'].idxmin())

Iteration # 	high PER 	low PER
Iteration 1 	Granny 	Road Runner
Iteration 2 	Sylvester 	Tasmanian Devil
Iteration 3 	Lola Bunny 	Tasmanian Devil
Iteration 4 	Lola Bunny 	Bugs Bunny
Iteration 5 	Granny 	Tweety
Iteration 6 	Foghorn Leghorn 	Marvin the Martian
Iteration 7 	Granny 	Tweety
Iteration 8 	Granny 	Road Runner
Iteration 9 	Lola Bunny 	Penelope
Iteration 10 	Daffy Duck 	Tweety

In [36]:
# Initialize four empty DataFrames, one for each 12-minute period.
number_of_iterations = 4
df_list = [pd.DataFrame(columns=game_stat_cols, index=list(ts_df['player_name'])) for i in range(number_of_iterations)]

# For each period, generate randomized player data and predict the PER.
# Use the model fitted earlier.
for df in df_list:
    for stat in game_stat_cols:
        df[stat] = list(ts_df[stat] + randn(len(ts_df)) * stdevs_s[stat])
    df['PER'] = lin_reg.predict(df)

# Concatenate the DataFrames and make the players' names the index.
game_df = pd.concat(df_list)
game_df.rename_axis('player_name', inplace=True)

# Create another index for the period in question.
minutes = [(x // len(ts_df)) * 12 for x in range(len(game_df))]
game_df['minutes'] = minutes
game_df.set_index('minutes', append=True, inplace=True)
game_df = game_df.swaplevel()

game_df

                                 TS%        AST         TO        USG  \
minutes player_name
0       Sylvester           0.621878  31.770126  14.540665  38.531820
        Marvin the Martian  0.609294  36.962030  15.206598  34.997838
        Road Runner         0.615992  27.995898  13.810719  30.867052
        Foghorn Leghorn     0.608944  32.574519  15.217328  32.349282
        Bugs Bunny          0.629272  31.941554  16.248286  34.632878
        Elmer Fudd          0.607970  30.720339  16.044805  37.677622
        Lola Bunny          0.630336  30.769124  13.669733  34.856792
        Porky Pig           0.596273  27.614814  15.785379  36.676460
        Tasmanian Devil     0.605943  29.225230  15.657420  33.476158
        Granny              0.613324  28.674882  16.734017  37.164086
        Wile E. Coyote      0.617873  29.946312  14.421038  35.162227
        Tweety              0.603628  25.871899  14.632015  36.497301
        Penelope            0.621789  26.677676  16.087873  28.573530
        Daffy Duck          0.627463  35.393559  14.827123  32.118616
12      Sylvester           0.613650  33.352370  15.180208  34.128272
        Marvin the Martian  0.607828  32.225656  14.029962  31.937301
        Road Runner         0.623386  26.069042  13.119344  36.210640
        Foghorn Leghorn     0.615756  30.345181  16.573069  32.147149
        Bugs Bunny          0.634903  30.725709  15.568337  34.688538
        Elmer Fudd          0.640367  27.916746  16.533728  35.160260
        Lola Bunny          0.629323  33.421831  13.365910  37.406555
        Porky Pig           0.627991  30.415531  15.170994  34.384774
        Tasmanian Devil     0.610752  30.180469  15.586639  40.497316
        Granny              0.610569  28.575860  14.092140  34.837842
        Wile E. Coyote      0.615858  29.932063  14.610845  32.954254
        Tweety              0.605857  25.865338  13.908061  37.539119
        Penelope            0.604333  26.420076  14.111894  29.131675
        Daffy Duck          0.632282  25.855656  14.851276  34.137461
24      Sylvester           0.643931  31.032044  14.949951  33.453865
        Marvin the Martian  0.622902  34.553217  13.840115  31.645259
        Road Runner         0.611568  30.351177  13.264113  36.413205
        Foghorn Leghorn     0.604310  32.200135  16.313080  35.925794
        Bugs Bunny          0.633502  32.320997  16.649971  32.969088
        Elmer Fudd          0.625634  29.473380  14.894423  35.547755
        Lola Bunny          0.644868  32.751934  15.143215  37.057207
        Porky Pig           0.611113  29.406327  14.583783  35.946315
        Tasmanian Devil     0.617218  24.419861  15.430552  33.440864
        Granny              0.622541  27.684684  14.386031  36.449544
        Wile E. Coyote      0.623971  30.496819  13.767863  36.513387
        Tweety              0.601799  24.611905  14.113237  34.279115
        Penelope            0.614126  27.195456  15.389485  26.707880
        Daffy Duck          0.625725  28.872314  13.219897  35.663495
36      Sylvester           0.621552  31.560683  16.840209  35.108822
        Marvin the Martian  0.605897  28.691818  14.256426  34.983666
        Road Runner         0.616750  27.370236  15.002507  37.545525
        Foghorn Leghorn     0.618000  33.764609  17.244365  36.141249
        Bugs Bunny          0.641328  29.946248  15.852447  34.855378
        Elmer Fudd          0.616260  26.034776  14.106924  35.686518
        Lola Bunny          0.644637  31.169735  13.198531  37.503843
        Porky Pig           0.605358  32.965350  16.161251  34.675982
        Tasmanian Devil     0.612510  25.973139  16.996905  35.917268
        Granny              0.616947  29.688528  14.200205  33.948425
        Wile E. Coyote      0.609712  34.984779  14.801344  35.178696
        Tweety              0.628440  28.615623  13.589246  38.184000
        Penelope            0.619067  24.798683  15.369281  31.294862
        Daffy Duck          0.617087  27.095132  14.075518  35.915733

                                  ORR        DRR       REBR        PER
minutes player_name
0       Sylvester            8.354463  20.291762  15.996035  33.280895
        Marvin the Martian   7.336841  23.709257  11.311795  22.223054
        Road Runner          7.265819  30.214046  13.794522  19.470872
        Foghorn Leghorn      3.640533  18.305370  13.731216  27.815557
        Bugs Bunny           6.539184  22.887987  12.051630  23.806187
        Elmer Fudd           7.570376  23.714498  11.926255  23.465478
        Lola Bunny           3.189000  19.710465  14.877981  32.056503
        Porky Pig            5.724919  21.492734  15.290861  28.551169
        Tasmanian Devil      5.290754  20.845479   7.138792  16.608126
        Granny               6.609762  22.150616  12.639885  25.078825
        Wile E. Coyote       7.154423  21.782435  13.041734  26.202035
        Tweety               5.190447  22.700409  11.475314  23.425543
        Penelope             7.418475  20.069957  11.623023  20.256060
        Daffy Duck           6.211734  23.381934  15.131153  27.379234
12      Sylvester            8.469989  21.608024  11.956562  23.523136
        Marvin the Martian   7.540469  18.795015   9.581041  21.088695
        Road Runner          7.633476  29.875348  11.237059  19.855013
        Foghorn Leghorn      6.455493  14.228538  14.460622  29.937024
        Bugs Bunny           4.650959  19.084650  15.046118  31.406188
        Elmer Fudd           4.959114  25.964953  15.754700  27.833876
        Lola Bunny           4.155950  24.819566  15.561908  31.497577
        Porky Pig            5.498933  17.954543  15.380560  31.972698
        Tasmanian Devil      5.463220  21.247954   9.451618  24.136012
        Granny               5.647601  19.750687  13.460495  27.859313
        Wile E. Coyote       6.977793  20.703839  16.700851  30.449725
        Tweety               4.875811  23.010651  10.185479  22.675710
        Penelope            10.008221  17.756864  14.203628  25.036022
        Daffy Duck           5.391542  21.740806  12.973210  26.142958
24      Sylvester            9.014297  18.724898   9.088038  22.410766
        Marvin the Martian   5.189864  26.529943   9.887265  18.333297
        Road Runner          3.870298  27.155810   9.750276  20.207057
        Foghorn Leghorn      6.495614  16.131192  15.820893  32.574196
        Bugs Bunny           3.448333  19.599737  13.459715  27.631308
        Elmer Fudd           4.015035  24.242929  17.725168  32.331907
        Lola Bunny           3.363431  20.705763  18.903223  38.500970
        Porky Pig            6.469107  20.963039  11.220479  24.294468
        Tasmanian Devil      4.539654  21.356298   7.988063  17.937109
        Granny               6.300853  22.233891  14.404719  28.864031
        Wile E. Coyote       7.123807  25.729511  15.969261  29.404232
        Tweety               9.380825  27.877928  13.664473  20.939954
        Penelope             8.799471  16.664757   7.404301  15.047422
        Daffy Duck           5.345959  18.349150  14.752309  32.468308
36      Sylvester            7.334921  16.531865  11.379811  26.086362
        Marvin the Martian   5.156201  27.844573  13.409488  22.642820
        Road Runner          7.833419  27.162444  12.710700  23.028327
        Foghorn Leghorn      5.225077  14.281987  11.624834  28.755580
        Bugs Bunny           5.184724  18.985266  13.008185  28.735634
        Elmer Fudd           5.113694  25.599320  13.566845  25.096131
        Lola Bunny           5.387438  20.287724  15.565096  34.800913
        Porky Pig            6.199325  14.978670  16.127083  33.258045
        Tasmanian Devil      4.560967  21.831086  10.444242  21.540427
        Granny               7.541280  23.293437  14.793591  26.919800
        Wile E. Coyote       6.260385  18.689418  16.633446  33.152992
        Tweety               6.035728  24.774967   9.306966  22.190700
        Penelope             9.114869  16.958775   8.052348  18.490044
        Daffy Duck           6.140772  18.120166  14.774893  31.450054

In [ ]:
game_df.to_csv('game_stats.csv')